### ISSUE TITLE
Verbose Mode

### ISSUE THREAD

**Issue by gchudnov** [zalando-incubator/clin#31]
It would be great to have _verbose mode_ in the tool.
When you run it now, you see:

```
⦿ Will update: event type event.type.1
⦿ Will update: event type event.type.2
⦿ Will update: event type event.type.3
...
✔ Up to date: event type event.type.4
...
```

but it is not entirely clear what kind of changes are going to happen in `⦿ Will update ...`

In this way it would be helpful to see the diff between the current state and new one.

**Comment by Dmitry-Erokhin** [comment]
Have you tried `-d` key?

**Comment by gchudnov** [comment]
indeed, it works,
thank you!

somehow hasn't found `-d` in the list of command line options
