### ISSUE TITLE
Outdated security contact

### ISSUE THREAD

**Issue by dlippok** [zalando-incubator/clin#75]
## Expected Behavior

Link in [SECURITY.md](https://github.com/zalando-incubator/clin/blob/master/SECURITY.md) leads to meaningful information on how to report security issues or apply for the Bug Bounty program on HackerOne.

## Actual Behavior

The provided link leads to corporate contact page that does not instruct how to report bugs or apply for bug bounty program.

## Steps to Reproduce the Problem

  1. Open [SECURITY.md](https://github.com/zalando-incubator/clin/blob/master/SECURITY.md)
  2. Click the link in the description (https://corporate.zalando.com/en/services-and-contact#security-form)

## Specifications

  - Version: n/a
  - Platform: n/a
  - Subsystem: n/a

**Comment by Dmitry-Erokhin** [comment]
Similar issue and resolution in other Z project: zalando/skipper#1929
